### ISSUE TITLE
Can I add new contributor to nodejs-ja?

### ISSUE THREAD

**Issue by watilde** [nodejs/Intl#42]
Since `nodejs-ja` don't have any maintainer/owner, we can't add more contributors. Could I have it?

**Comment by addaleax** [comment]
I don’t know what the right place to ask this is, but I *think* it might be nodejs/TSC rather than this repo.

@nodejs/tsc I’ve gone ahead and made @watilde a team maintainer of @nodejs/nodejs-ja, it doesn’t look like there’s any difference besides the ability to add members to the team. Let me know if this is a kind of thing that should be handled differently!

(edit: closing, but please reopen if there’s something we need to talk about)

**Comment by srl295** [comment]
@addaleax what you said.

**Comment by watilde** [comment]
Thanks! I could add one contributor who is a member of Website WG, but I couldn't add a new contributor.
+ https://github.com/nodejs/nodejs-ja/pull/120

I will open an issue on TSC later then :)
