### ISSUE TITLE
Utilize intl options without an local

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/Intl#46]
I want to use `Intl.DateTimeFormat` with some options but it don't seem possible to use it without specifying a local as first parameter and i want it to be localized, i don't want to have to force one language.

**Comment by bnoordhuis** [comment]
I don't really understand what you're asking.  Post sample code maybe?

**Comment by jimmywarting** [comment]
figured out you could just pass undefined

```js
const format = new Intl.DateTimeFormat(undefined, {
  year: 'numeric',
  month: 'long',
  day: 'numeric',
  hour: 'numeric',
  minute: 'numeric',
  second: 'numeric',
  timeZoneName: 'short',
}).format;
```

I would wish this was possible:

```js
const format = new Intl.DateTimeFormat({
  year: 'numeric',
  month: 'long',
  day: 'numeric',
  hour: 'numeric',
  minute: 'numeric',
  second: 'numeric',
  timeZoneName: 'short',
}).format;
```

**Comment by bnoordhuis** [comment]
Ah, okay.  Intl's behavior is governed by ECMA 402.  You'd have to take it up with the committee behind that spec to get that changed.

**Comment by srl295** [comment]
@jimmywarting I understand what you are saying from an API point of view, but ultimately using this function "without a locale" doesn't work because these are locale sensitive functions.  Using undefined (or an empty list) specifies to use the JavaScript container's default. See https://tc39.github.io/ecma402/#sec-intl-datetimeformat-constructor for the constructor's definition and  https://tc39.github.io/ecma402/#sec-canonicalizelocalelist for the operation that takes in the undefined or `[]`. 

In any event, the behavior will be that you will get the default locale.

**Comment by srl295** [comment]
answered
